app/api/urls.py
from django.urls import path
from .views import api_overview, task_list

urlpatterns = [
    path('', api_overview, name='api-overview'),
    path('task-list/', task_list, name='task-list'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('weatherapp.urls')),
    path('api/', include('api.urls')),
    path('', include('szymon_site.urls')),

    path('auth/', include('authorization.urls')),
    path('imageupload/', include('images_api.urls')),
    path('reminder/', include('reminder.urls')),
    path('create_mp3_translations/', include('save_mp3_translations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
        )
    

app/save_mp3_translations/urls.py
from django.urls import path
from .views import create_mp3_from_words, wczytaj_dane, WordPairsAPIView, export_wordpairs_csv, create_mp3_finn

urlpatterns = [
    path('csv/', export_wordpairs_csv, name="export-csv"),
    path('wczytaj/', wczytaj_dane, name="wczytaj_dane"),
    path('wordspairlist/', WordPairsAPIView.as_view(), name='word-pair-list-api-view'),
    # path('randompairs/', RandomWordPairsAPIView.as_view(), name='random-pairs'),
    path('', create_mp3_from_words, name='create-mp3'),
    path('finn/', create_mp3_finn, name='create-mp3-finn'),
]

app/save_mp3_translations/models.py
from django.db import models

# Create your models here.

class Language(models.Model):
    name = models.CharField(max_length=250)
    abbrev = models.CharField(max_length=10)


class Word(models.Model):
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    word = models.CharField(max_length=50)

    def __str__(self):
        return self.word


class WordsPair(models.Model):
    base_word = models.ForeignKey(Word, related_name='base_word', on_delete=models.CASCADE)
    translated_word = models.ForeignKey(Word, related_name='translated_word', on_delete=models.CASCADE)
    base_word_sentence = models.CharField(max_length=150, null=True, blank=True)
    translated_word_sentence = models.CharField(max_length=150, null=True, blank=True)
    

app/save_mp3_translations/forms.py
from django import forms

lang_choices = [
    ("en", "English"),
    ("pl", "Polish"),
    ("hr", "Croatian"),
    ("fr", "French"),
    ("ru", "Russian"),
    ("es", "Spanish"),
    ("ko", "Korean"),
    ("zh-CN", "Chinese (simplified)")
]


class MP3FinnForm(forms.Form):
    words1 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count1 = forms.IntegerField(max_value=5, min_value=1)
    words2 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count2 = forms.IntegerField(max_value=5, min_value=1)
    words3 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count3 = forms.IntegerField(max_value=5, min_value=1)
    words4 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count4 = forms.IntegerField(max_value=5, min_value=1)
    words5 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count5 = forms.IntegerField(max_value=5, min_value=1)
    words6 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count6 = forms.IntegerField(max_value=5, min_value=1)
    words7 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count7 = forms.IntegerField(max_value=5, min_value=1)
    words8 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count8 = forms.IntegerField(max_value=5, min_value=1)
    words9 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count9 = forms.IntegerField(max_value=5, min_value=1)
    words10 = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=100, required=False)
    count10 = forms.IntegerField(max_value=5, min_value=1)

    enter_language = forms.ChoiceField(label='Choose enter language', choices=lang_choices, initial='en')
    destination_language = forms.ChoiceField(label='Choose destination language', choices=lang_choices, initial='pl')


class MP3Form(forms.Form):
    words = forms.CharField(label='Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"', max_length=3000)
    enter_language = forms.ChoiceField(label='Choose enter language', choices=lang_choices, initial='en')
    destination_language = forms.ChoiceField(label='Choose destination language', choices=lang_choices, initial='pl')
   

app/save_mp3_translations/views.py
import os
import pandas as pd
from .models import Language, Word, WordsPair
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.decorators import api_view
from rest_framework import generics
from .serializers import WordsPairSerializer
from .forms import MP3Form, MP3FinnForm
from googletrans import Translator
from io import BytesIO
import re

from gtts import gTTS
from pydub import AudioSegment
import csv


@api_view(['POST', 'GET'])
def create_mp3_from_words(request):
    if request.method == 'POST':
        form = MP3Form(request.POST)
        if form.is_valid():
            text = form.cleaned_data['words']
            sentences = re.split(r'[.!?]', text)
            sentences = [sentence.strip() for sentence in sentences if sentence.strip()]

            enter_language = form.cleaned_data['enter_language']
            destination_language = form.cleaned_data['destination_language']
       
            final_audio = None
            translator = Translator()

            for sentence in sentences:
                enter_audio_io = BytesIO()
                translated_audio_io = BytesIO()
                try:
                    translated_text = translator.translate(sentence, src=enter_language, dest=destination_language).text

                    tts_enter = gTTS(sentence, lang=enter_language)
                    tts_enter.write_to_fp(enter_audio_io)

                    tts_dest = gTTS(translated_text, lang=destination_language)
                    tts_dest.write_to_fp(translated_audio_io)

                except Exception as e:
                    # print the exception to command
                    print("An error occurred: %s", e)
                enter_audio_io.seek(0)
                translated_audio_io.seek(0)

                enter_audio = AudioSegment.from_file(enter_audio_io, format="mp3")
                translated_audio = AudioSegment.from_file(translated_audio_io, format="mp3")
                empty_segment_duration_multiplier = len(sentence) // 10
                duration = 1000 * empty_segment_duration_multiplier
                if duration < 2001:
                    duration = 2500
                if duration > 7000:
                    duration = 7000
                empty_segment = AudioSegment.silent(duration=duration)
                if final_audio:
                    final_audio += enter_audio + translated_audio + empty_segment
                else:
                    final_audio = enter_audio + translated_audio + empty_segment

            audio_io = BytesIO()
            final_audio.export(audio_io, format="mp3")
            audio_io.seek(0)

            response = HttpResponse(audio_io, content_type='audio/mp3')
            # final_audio.export(response, format="mp3")
            response['Content-Disposition'] = 'attachment; filename="generated.mp3"'
            return response
    else:
        form = MP3Form()
        max_length = form.fields['words'].max_length

    return render(request, 'mp3translations.html', {'form': form, 'max_length': max_length})


@api_view(['POST', 'GET'])
def create_mp3_finn(request):
    max_length = None
    if request.method == 'POST':
        form = MP3FinnForm(request.POST)
        sentences = []
        if form.is_valid():
            for i in range(1,11):
                sentence = form.cleaned_data[f"words{i}"]
                if sentence != "":
                    counter = form.cleaned_data[f"count{i}"]
                    for j in range(counter):
                        sentences.append(sentence)


            # text = form.cleaned_data['words']
            # sentences = re.split(r'[.!?]', text)
            # sentences = [sentence.strip() for sentence in sentences if sentence.strip()]

            enter_language = form.cleaned_data['enter_language']
            destination_language = form.cleaned_data['destination_language']
       
            final_audio = None
            translator = Translator()

            for sentence in sentences:
                enter_audio_io = BytesIO()
                translated_audio_io = BytesIO()
                try:
                    translated_text = translator.translate(sentence, src=enter_language, dest=destination_language).text

                    tts_enter = gTTS(sentence, lang=enter_language)
                    tts_enter.write_to_fp(enter_audio_io)

                    tts_dest = gTTS(translated_text, lang=destination_language)
                    tts_dest.write_to_fp(translated_audio_io)

                except Exception as e:
                    # print the exception to command
                    print("An error occurred: %s", e)
                enter_audio_io.seek(0)
                translated_audio_io.seek(0)

                enter_audio = AudioSegment.from_file(enter_audio_io, format="mp3")
                translated_audio = AudioSegment.from_file(translated_audio_io, format="mp3")
                empty_segment_duration_multiplier = len(sentence) // 10
                duration = 1000 * empty_segment_duration_multiplier
                if duration < 2001:
                    duration = 2500
                if duration > 7000:
                    duration = 7000
                empty_segment = AudioSegment.silent(duration=duration)
                if final_audio:
                    final_audio += enter_audio + translated_audio + empty_segment
                else:
                    final_audio = enter_audio + translated_audio + empty_segment

            audio_io = BytesIO()
            final_audio.export(audio_io, format="mp3")
            audio_io.seek(0)

            response = HttpResponse(audio_io, content_type='audio/mp3')
            # final_audio.export(response, format="mp3")
            response['Content-Disposition'] = 'attachment; filename="generated.mp3"'

            return response
    else:
        
        form = MP3FinnForm()
        max_length = form.fields['words1'].max_length

    return render(request, 'finn.html', {'form': form, 'max_length': max_length})




def wczytaj_dane(request):
    biezacy_katalog = os.path.dirname(os.path.abspath(__file__))
    # Utworzenie ścieżki do pliku Excel
    sciezka_do_pliku_excel = os.path.join(biezacy_katalog, 'to_load', 'Czasowniki.xlsx')
    df = pd.read_excel(sciezka_do_pliku_excel, header=None)
    print(df)

    for _, row in df.items():
        for index, (column_name, value) in enumerate(row.items()):
    # Check if the value and the next value (if exists) are not null
            if not pd.isnull(value) and (index + 1 < len(row)):  # Check if index+1 is within range
                _, next_value = list(row.items())[index + 1]  # Get the next value
                if not pd.isnull(next_value):
                    # print("Both current and next values are not null.")
                    print(value, "   ", next_value, type(value))
                    language_chorwacki, created = Language.objects.get_or_create(name='Chorwacki', abbrev='hr')
                # Sprawdzenie czy język polski istnieje w bazie danych
                    language_polski, created = Language.objects.get_or_create(name='Polski', abbrev='pl')
                    # Tworzenie obiektu Word dla słowa chorwackiego
                    word_chorwackie, created = Word.objects.get_or_create(language=language_chorwacki, word=value)
                    # Tworzenie obiektu Word dla słowa polskiego
                    word_polskie, created = Word.objects.get_or_create(language=language_polski, word=next_value)

                    # Tworzenie obiektu WordsPair i zapisanie go do bazy danych
                    words_pair = WordsPair(base_word=word_chorwackie, translated_word=word_polskie)
                    words_pair.save()
                else:
                    pass

    return HttpResponse("<h1>Page was found</h1>")


class WordPairsAPIView(generics.ListAPIView):
    queryset = WordsPair.objects.all()
    serializer_class = WordsPairSerializer



def export_wordpairs_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="wordpairs.csv"'

    writer = csv.writer(response)
    writer.writerow(['base_word', 'translated_word', 'translated_word_sentence'])

    wordpairs = WordsPair.objects.all().values_list('base_word', 'translated_word', 'translated_word_sentence')
    for wordpair in wordpairs:
        writer.writerow(wordpair)

    return response



# class RandomWordPairsAPIView(generics.ListAPIView):
    # serializer_class = WordsPairSerializer

    # def get_queryset(self):
    #     queryset = WordsPair.objects.all()
    #     counter = WordsPair.objects.count()
    #     sublist_number = 20

    #     items_per_sublist = counter // sublist_number
    #     print(counter)
    #     print(items_per_sublist)

    #     iterator = 0
    #     przeskok = 25
    #     empty_segment = AudioSegment.silent(duration=2500)
    #     outerator = 0
    #     # for i in range(3):
    #     while outerator < counter:
    #         outerator = iterator + przeskok
    #         if outerator > counter:
    #             outerator = counter

    #         sublist_queryset = queryset[iterator:outerator]
    #         final_audio = None
            

    #         for wordspair in sublist_queryset:
    #             tts_pl = gTTS(wordspair.translated_word.word, lang='pl')
    #             tts_hr = gTTS(wordspair.base_word.word, lang='hr')
    #             # with open(f"{wordspair.translated_word.word}-{wordspair.base_word.word}.mp3", 'wb') as f:
    #             #     tts_pl.write_to_fp(f)
    #             #     tts_hr.write_to_fp(f)

    #             # Save translations to temporary files
    #             tts_pl.save("pl1.mp3")
    #             tts_hr.save("hr1.mp3")

    #             # Load translations as audio segments
    #             audio_pl = AudioSegment.from_mp3("pl1.mp3")
    #             audio_hr = AudioSegment.from_mp3("hr1.mp3")

app/save_mp3_translations/templates/save_mp3_translations/finn.html
<!DOCTYPE html>

<html>
<head>
    <title>Create MP3</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mp3_style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Write Your text and create MP3 to learn languages!</h2>
        <form id="mp3-form" method="post">
            {% csrf_token %}
            
            <label for="id_words">Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"</label>
            <!-- {{ form.words }} -->
            <div>
                <!-- Pętla generująca inputy tekstowe z pętlą dla każdego selecta -->
                <div class="sentence">
                    <input id="id_words1" name="words1" type="text">
                    <select name="count1">
                        <option value="1" selected>1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
                <div class="sentence">
                    <input id="id_words2" name="words2" type="text">
                    <select name="count2">
                        <option value="1" selected>1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
                <div class="sentence">
                <input id="id_words3" name="words3" type="text">
                <select name="count3">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words4" name="words4" type="text">
                <select name="count4">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words5" name="words5" type="text">
                <select name="count5">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words6" name="words6" type="text">
                <select name="count6">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words7" name="words7" type="text">
                <select name="count7">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words8" name="words8" type="text">
                <select name="count8">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words9" name="words9" type="text">
                <select name="count9">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
                <div class="sentence">
                <input id="id_words10" name="words10" type="text">
                <select name="count10">
                    <option value="1" selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </div>
    
            </div>
           
            <label for="id_enter_language">Choose enter language</label>
            {{ form.enter_language }}
            <label for="id_destination_language">Choose destination language</label>
            {{ form.destination_language }}
            <button type="submit">Generate MP3</button>
        </form>
    </div>
    <script>
        document.getElementById('mp3-form').addEventListener('submit', function(event) {
            var max_length = 1000; // Zakładam, że maksymalna długość to 100 znaków
            var inputs = document.querySelectorAll('.sentence input[type="text"]');
            var words = "";
            inputs.forEach(function(input) {
                words += input.value.trim() + " ";
            });
            words = words.trim(); // Usuwa białe znaki z początku i końca
            if (words.length === 0) {
                alert('Type at least one word.')
                event.preventDefault(); // Blokuj domyślną akcję przesyłania formularza
            }
            if (words.length > max_length) {
                alert('You have exceeded the maximum number of characters allowed.')
                event.preventDefault(); // Blokuj domyślną akcję przesyłania formularza
            }
        });
    </script>

</body>

</html>

app/save_mp3_translations/templates/save_mp3_translations/mp3translations.html
<!DOCTYPE html>

<html>
<head>
    <title>Create MP3</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'mp3_style.css' %}">
</head>
<body>
    <div class="container">
        <h2>Write Your text and create MP3 to learn languages!</h2>
        <form id="mp3-form" method="post">
            {% csrf_token %}
            <label for="id_words">Enter sentences or words. Remember to end every sentence/word with ".", "!" or "?"</label>
            <!-- {{ form.words }} -->
            <textarea id="id_words" name="words" rows="5" data-max-length="{{ max_length }}"></textarea> <!-- Użyj textarea zamiast input -->
            <label for="id_enter_language">Choose enter language</label>
            {{ form.enter_language }}
            <label for="id_destination_language">Choose destination language</label>
            {{ form.destination_language }}
            <button type="submit">Generate MP3</button>
        </form>
    </div>
    <script>
        document.getElementById('mp3-form').addEventListener('submit', function(event) {
            var max_length = document.getElementById('id_words').getAttribute('data-max-length');
            var words = document.getElementById('id_words').value;
            if (words.length === 0) {
                alert('Type at least one word.')
                event.preventDefault(); // Blokuj domyślną akcję przesyłania formularza
            }
            if (words.length > max_length) {
                alert('You have exceeded the maximum number of characters allowed.')
                event.preventDefault(); // Blokuj domyślną akcję przesyłania formularza
            }
        });
    </script>

</body>

</html>