app/api/urls.py
from django.urls import path
from .views import api_overview, task_list

urlpatterns = [
    path('', api_overview, name='api-overview'),
    path('task-list/', task_list, name='task-list'),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('weatherapp.urls')),
    path('api/', include('api.urls')),
    path('', include('szymon_site.urls')),

    path('auth/', include('authorization.urls')),
    path('imageupload/', include('images_api.urls')),
    path('reminder/', include('reminder.urls')),
    path('create_mp3_translations/', include('save_mp3_translations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
        )
    

app/reminder/urls.py
from django.urls import path
from .views import RemindingMessagesListCreateAPIView, RemindingMessageDetailAPIView


urlpatterns = [
    path('', RemindingMessagesListCreateAPIView.as_view(), name='reminding-messages-list'),
    path('<int:pk>/', RemindingMessageDetailAPIView.as_view(), name='message-details'),
]

app/reminder/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class RemindingMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=500, default="Just reminding sth")
    created_at = models.DateTimeField(auto_now_add=True)
    send_mail_at = models.DateTimeField()

    def __str__(self):
        return self.message

app/reminder/forms.py
from django import forms

class MessageForm(forms.Form):
    message = forms.CharField(max_length=255, required=True)
    send_mail_at = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

app/reminder/views.py
from rest_framework import generics
from .serializers import RemindingMessagesSerializer
from .models import RemindingMessage
from .tasks import send_reminding_email
from rest_framework.response import Response
import os
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.views import APIView
from django.http import response
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework import status
from django.contrib.auth.models import User
from .forms import MessageForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from rest_framework.permissions import IsAuthenticatedOrReadOnly


class RemindingMessagesListCreateAPIView(generics.ListCreateAPIView, View):
    queryset = RemindingMessage.objects.all()
    serializer_class = RemindingMessagesSerializer
    form = MessageForm()
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get(self, request):
        user = self.request.user
        if user.is_authenticated:
            user_messages = RemindingMessage.objects.filter(user=user.id)
            return render(request, 'reminding_messages.html', {'form': self.form, 'messages': user_messages})
        login_page_url = request.build_absolute_uri(reverse(('authorization')))
        return render(request, 'reminding_messages.html', {'form': self.form, 'messages': None, 'login_page_url': login_page_url})

    def post(self, request):
        
        if request.data:
            # API request, use serializer
            data = request.data.copy()
            data['user'] = request.user.id

            serializer = self.get_serializer(data=data)
            if serializer.is_valid():
                serializer.save()
                message_id = serializer.data["id"]
                send_mail_at = serializer.data['send_mail_at']
       
                params = {
                    'message_id': message_id, 
                    'smtp_server': os.environ.get("EMAIL_HOST"), 
                    'sender_email': os.environ.get("EMAIL_HOST_USER"), 
                    'password': os.environ.get("EMAIL_HOST_PASSWORD"), 
                    'email_port': os.environ.get("EMAIL_PORT")
                    }
                send_reminding_email.apply_async(args=[], kwargs=params, eta=send_mail_at)
                return render(request, 'reminding_messages.html', {'form': self.form, 'messages': self.get_queryset()})
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        else:
            # HTML form request
            form = MessageForm(request.POST)
            if form.is_valid():
                message = form.cleaned_data['message']
                send_mail_at = form.cleaned_data['send_mail_at']
                user = request.user
                message_obj = RemindingMessage(message=message, send_mail_at=send_mail_at, user=user)
                message_obj.save()
                return HttpResponseRedirect(reverse('reminding-messages-list'))
            return render(request, 'reminding_messages.html', {'form': form, 'user': request.user})
    
class RemindingMessageDetailAPIView(generics.RetrieveAPIView):
    queryset = RemindingMessage.objects.all()
    serializer_class = RemindingMessagesSerializer
    lookup_field = 'pk'
# class RemindingMessagesListCreateAPIView(APIView):
#     queryset = RemindingMessage.objects.all()
#     serializer_class = RemindingMessagesSerializer
#     renderer_classes = [TemplateHTMLRenderer]
#     template_name = 'reminding_messages.html'


#     def get(self, request, format=None):
#         queryset = RemindingMessage.objects.all()
#         serializer = RemindingMessagesSerializer()
#         return Response({'queryset': queryset, 'serializer': serializer})


#     def post(self, request, format=None):
#         serializer = RemindingMessagesSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response({'serializer': serializer}, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

































# class RemindingMessagesListCreateAPIView(generics.ListCreateAPIView):
#     queryset = RemindingMessage.objects.all()
#     serializer_class = RemindingMessagesSerializer
#     renderer_classes = [TemplateHTMLRenderer]
#     template_name = 'reminding_messages.html'
# class RemindingMessagesListCreateAPIView(APIView):
#     queryset = RemindingMessage.objects.all()
#     serializer_class = RemindingMessagesSerializer
#     renderer_classes = [TemplateHTMLRenderer]
#     template_name = 'reminding_messages.html'


#     def get(self, request, format=None):
#         queryset = RemindingMessage.objects.all()
#         serializer = RemindingMessagesSerializer()
#         return Response({'queryset': queryset, 'serializer': serializer})


#     def post(self, request, format=None):
#         serializer = RemindingMessagesSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response({'serializer': serializer}, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    # def perform_create(self, reminding_messages_serializer):
    #     if reminding_messages_serializer.is_valid():
    #         reminding_messages_serializer.save()
    #         message_id = reminding_messages_serializer.data["id"]
    #         reminding_message = RemindingMessage.objects.get(id=message_id)
    #         user_email = reminding_message.user.email
    #         send_mail_at = reminding_message.send_mail_at
    #         message = reminding_message.message
    #         created_at = reminding_message.created_at

    #         smtp_server = os.environ.get("EMAIL_HOST")
    #         sender_email = os.environ.get("EMAIL_HOST_USER")
    #         password = os.environ.get("EMAIL_HOST_PASSWORD")
    #         email_port = os.environ.get("EMAIL_PORT")
    #         params = [message_id, user_email, message, created_at]
    #         server_variables = [smtp_server, sender_email, password, email_port]
          
    #         
    #     return Response(reminding_messages_serializer.data, template_name=self.template_name)
   

app/reminder/templates/reminder/reminder_base.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'reminder_style.css' %}">
</head>
<body>
    {% block content %}{% endblock content %} 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="{% static 'scripts.js' %}"></script>
</body>
</html>

app/reminder/templates/reminder/reminding_messages.html
{% extends 'reminder_base.html' %}
{% load static %}



{% block content %}
<div class="container">
    <div class="col-8 message-list">
        <h1 style="padding-bottom: 20px;">Twoje zapisane przypominajki</h1>
        {% if login_page_url %}
        Zaloguj się, by móc utworzyć przypominajki: <br>
        <a href="{{ login_page_url }}">Login</a>
        {% endif %}
        <ul class="message-items">
            
            {% for message in messages %}
                <li class="message-item">
                    <a href="{% url 'message-details' message.id %}">
                    <div class="message-text">
                        {{ message.message|truncatewords:10 }}
                        <br>
                        <hr>
                        <br>Wiadomość zostanie wysłana: <br>  
                        {{ message.send_mail_at|date:"Y-m-d H:i" }}
                    </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-4 create-message">
    
        <h1>Utwórz nową przypominajkę</h1>
        <!-- HTML Form for Creating Messages -->
            <form method="post" class="form-container">
                {% csrf_token %}

                <label for="id_message">Wpisz, o czym mam Ci przypomnieć:</label>
                <!-- <input type="text" id="id_message" name="message" required><br> -->
                <textarea id="id_message" name="message" class="form-textarea-date-button" required></textarea><br>

                <label for="id_send_mail_at">Wybierz, kiedy mam Ci wysłać e-mail z tą wiadomością:</label>
                <input type="datetime-local" id="id_send_mail_at" name="send_mail_at" class="form-textarea-date-button" required><br>

                <button type="submit" class="form-textarea-date-button">Stwórz przypominajkę</button>
            </form>
    </div>
</div>
{% endblock content %}

